//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.DAL.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class IQ_InvoiceHedar_Tax
    {
        public Nullable<int> CompCode { get; set; }
        public int InvoiceID { get; set; }
        public Nullable<int> TrNo { get; set; }
        public string RefNO { get; set; }
        public Nullable<int> RefTrID { get; set; }
        public Nullable<System.DateTime> TrDate { get; set; }
        public Nullable<int> TrType { get; set; }
        public Nullable<bool> IsCash { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<int> VatType { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> NetAfterVat { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<System.TimeSpan> TrTime { get; set; }
        public Nullable<int> TaxCurrencyID { get; set; }
        public Nullable<int> InvoiceCurrenyID { get; set; }
        public Nullable<decimal> ItemTotal { get; set; }
        public Nullable<decimal> ItemAllowTotal { get; set; }
        public Nullable<decimal> ItemDiscountTotal { get; set; }
        public Nullable<decimal> ItemVatTotal { get; set; }
        public string UUID { get; set; }
        public string DocType { get; set; }
        public Nullable<decimal> RoundingAmount { get; set; }
        public Nullable<System.DateTime> TimeUpload { get; set; }
        public string VersionInv { get; set; }
        public Nullable<int> GlobalInvoiceCounter { get; set; }
        public int receiverID_rec { get; set; }
        public Nullable<int> branchID_rec { get; set; }
        public string country_rec { get; set; }
        public string governate_rec { get; set; }
        public string regionCity_rec { get; set; }
        public string street_rec { get; set; }
        public string buildingNumber_rec { get; set; }
        public string postalCode_rec { get; set; }
        public string floor_rec { get; set; }
        public string room_rec { get; set; }
        public string landmark_rec { get; set; }
        public string additionalInformation_rec { get; set; }
        public string type_rec { get; set; }
        public string id_rec { get; set; }
        public string name_rec { get; set; }
        public int issuerID_iss { get; set; }
        public Nullable<int> branchID_iss { get; set; }
        public string country_iss { get; set; }
        public string governate_iss { get; set; }
        public string regionCity_iss { get; set; }
        public string street_iss { get; set; }
        public string buildingNumber_iss { get; set; }
        public string postalCode_iss { get; set; }
        public string floor_iss { get; set; }
        public string room_iss { get; set; }
        public string landmark_iss { get; set; }
        public string additionalInformation_iss { get; set; }
        public string type_iss { get; set; }
        public string id_iss { get; set; }
        public string name_iss { get; set; }
        public string CurrencyCode { get; set; }
        public string DescA { get; set; }
        public string DescL { get; set; }
        public string Remarks { get; set; }
        public string ClientSecret { get; set; }
        public string ClientID { get; set; }
        public string DocPDFFolder { get; set; }
        public string ActivityCode { get; set; }
        public string TypeVersion { get; set; }
        public string TokenPinCode { get; set; }
        public string Tokentype { get; set; }
    }
}
